export enum IssueStatus {
  SUBMITTED = 'submitted',
  ACKNOWLEDGED = 'acknowledged',
  UNDER_REVIEW = 'under-review',
  IN_PROGRESS = 'in-progress',
  AWAITING_CUSTOMER_RESPONSE = 'awaiting-customer-response',
  ESCALATED = 'escalated',
  SCHEDULED = 'scheduled',
  TESTING = 'testing',
  RESOLVED = 'resolved',
  CLOSED = 'closed',
  REOPENED = 'reopened',
  ON_HOLD = 'on-hold',
  PENDING_THIRD_PARTY = 'pending-third-party',
  PLANNED_FOR_FUTURE_RELEASE = 'planned-for-future-release',
  CANNOT_REPRODUCE = 'cannot-reproduce',
  NOT_A_BUG = 'not-a-bug',
  DUPLICATE = 'duplicate',
}
