name: Deploy

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: _token
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.digitalocean.com/floumy-registry/api:latest

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            doctl registry login
            docker pull registry.digitalocean.com/floumy-registry/api:latest
            docker stop api || true
            docker rm api || true
            docker run -d --restart=always --name api -e FRONTEND_URL=https://app.floumy.com -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_DATABASE=${{ secrets.DB_DATABASE }} -e SPACES_KEY=${{ secrets.SPACES_KEY }} -e SPACES_SECRET=${{ secrets.SPACES_SECRET }} -e SPACES_ENDPOINT=${{ secrets.SPACES_ENDPOINT }} -e SPACES_REGION=${{ secrets.SPACES_REGION }} -e SPACES_FORCE_PATH_STYLE=${{ secrets.SPACES_FORCE_PATH_STYLE }} -e SPACES_BUCKET=${{ secrets.SPACES_BUCKET }} -e MAIL_USER=${{ secrets.MAIL_USER }} -e POSTMARK_API_KEY=${{ secrets.POSTMARK_API_KEY }} -p 4000:8080 registry.digitalocean.com/floumy-registry/api:latest
            docker image prune -f
