name: Deploy

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: _token
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.digitalocean.com/floumy/api:latest

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            doctl auth switch --context floumy
            doctl registry login
            docker pull registry.digitalocean.com/floumy/api:latest
            docker stop api || true
            docker rm api || true
            docker run -d --restart=always --name api -e DB_HOST=floumy-db -e DB_USERNAME=floumy -e DB_PASSWORD=floumy -e DB_DATABASE=floumy --network=floumy -p 4000:8080 registry.digitalocean.com/floumy/api:latest
            docker image prune -f
