name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            VERSION=${{ github.ref_name }}
            docker pull docker.io/floumy/api:${VERSION}
            docker stop api || true
            docker rm api || true
            docker run --network host \
            -d --restart=always \
            --name api \
            -v /var/log/floumy:/usr/src/log/ \
            -e FRONTEND_URL=https://app.floumy.com \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
            -e DB_SSL=${{ secrets.DB_SSL }} \
            -e DB_SSL_CERTIFICATE="${{ secrets.DB_SSL_CERTIFICATE }}" \
            -e SPACES_KEY=${{ secrets.SPACES_KEY }} \
            -e SPACES_SECRET=${{ secrets.SPACES_SECRET }} \
            -e SPACES_ENDPOINT=${{ secrets.SPACES_ENDPOINT }} \
            -e SPACES_REGION=${{ secrets.SPACES_REGION }} \
            -e SPACES_FORCE_PATH_STYLE=${{ secrets.SPACES_FORCE_PATH_STYLE }} \
            -e SPACES_BUCKET=${{ secrets.SPACES_BUCKET }} \
            -e MAIL_USER=${{ secrets.MAIL_USER }} \
            -e POSTMARK_API_KEY=${{ secrets.POSTMARK_API_KEY }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }} \
            -e STRIPE_SUCCESS_URL=${{ secrets.STRIPE_SUCCESS_URL }} \
            -e STRIPE_CANCEL_URL=${{ secrets.STRIPE_CANCEL_URL }} \
            -e STRIPE_BUILD_IN_PRIVATE_PRICE_ID=${{ secrets.STRIPE_BUILD_IN_PRIVATE_PRICE_ID }} \
            -e STRIPE_BUILD_IN_PUBLIC_PRICE_ID=${{ secrets.STRIPE_BUILD_IN_PUBLIC_PRICE_ID }} \
            -e STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }} \
            -e GITHUB_CLIENT_ID=${{ secrets.GHUB_CLIENT_ID }} \
            -e GITHUB_CLIENT_SECRET=${{ secrets.GHUB_CLIENT_SECRET }} \
            -e GITHUB_REDIRECT_URI=${{ secrets.GHUB_REDIRECT_URI }} \
            -e GITHUB_WEBHOOK_URL_BASE=${{ secrets.GHUB_WEBHOOK_URL_BASE }} \
            -e GITHUB_WEBHOOK_SECRET=${{ secrets.GHUB_WEBHOOK_SECRET }} \
            -e GITLAB_WEBHOOK_URL_BASE=${{ secrets.GITLAB_WEBHOOK_URL_BASE }} \
            -e GITLAB_WEBHOOK_SECRET=${{ secrets.GITLAB_WEBHOOK_SECRET }} \
            -e LANGSMITH_TRACING=${{ secrets.LANGSMITH_TRACING }} \
            -e LANGSMITH_ENDPOINT=${{ secrets.LANGSMITH_ENDPOINT }} \
            -e LANGSMITH_API_KEY=${{ secrets.LANGSMITH_API_KEY }} \
            -e LANGSMITH_PROJECT=${{ secrets.LANGSMITH_PROJECT }} \
            -p 4000:8080 docker.io/floumy/api:${VERSION}
            docker image prune -f

  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Web to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP_WEB }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            VERSION=${{ github.ref_name }}
            docker pull docker.io/floumy/web:${VERSION}
            docker stop web-app || true
            docker rm web-app || true
            docker run -d --restart=always --name web-app \
            -e REACT_APP_API_URL=https://api.floumy.com \
            -p 3000:80 docker.io/floumy/web:${VERSION}
            docker image prune -f
