name: Publish to Docker Hub

on:
  push:
    tags:
      - '*'


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: floumy
          POSTGRES_PASSWORD: floumy
          POSTGRES_DB: floumy

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.13.1'

      - name: Install dependencies
        working-directory: ./api
        run: npm ci

      - name: Lint API code
        working-directory: ./api
        run: |
          npm run lint:check

      - name: Lint Web code
        working-directory: ./web
        run: |
          npm ci
          npm run lint:check

      - name: Run tests
        working-directory: ./api
        run: cp .env.ci .env && npm run test

  push_web_to_registry:
    name: Push Web Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: floumy

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: floumy/web
          tags: |
            type=raw,value=latest
            type=ref,event=tag

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          file: ./web/Dockerfile
          context: ./web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/floumy/web
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
  push_api_to_registry:
    name: Push API Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: floumy

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: floumy/api
          tags: |
            type=raw,value=latest
            type=ref,event=tag

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          file: ./api/Dockerfile
          context: ./api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/floumy/api
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
