name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: floumy
          POSTGRES_PASSWORD: floumy
          POSTGRES_DB: floumy

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.13.1'

      - name: Install dependencies
        working-directory: ./api
        run: npm ci

      - name: Run tests
        working-directory: ./api
        run: cp .env.ci .env && npm run test
