name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Pull PostgreSQL image
        run: |
          docker pull postgres:13

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.13.1'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
