name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Start PostgreSQL container
        run: |
          docker run --name postgres -e POSTGRES_USER=testuser -e POSTGRES_PASSWORD=testpass -e POSTGRES_DB=testdb -d postgres:latest
          sleep 20 # wait for the database to start
          docker exec -u postgres postgres psql -c "ALTER SYSTEM SET max_connections = '200';"
          docker restart postgres
          sleep 20 # wait for the database to restart

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.13.1'

      - name: Install dependencies
        run: npm ci

      - name: Run test with coverage
        run: npm run test:cov

      - name: Upload coverage to a service
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
